apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["sleep"]
    args: ["36000"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "300m"
      limits:
        memory: "128Mi"
        cpu: "300m"

